dependencies:
- ipywidgets==8.1.2
- jupyter-archive==3.4.0
- jupyter-resource-usage==1.1.0
- jupyter-server-proxy==4.4.0
- jupyter-rsession-proxy==2.2.1
- jupyter-syncthing-proxy==1.0.3
- jupyterhub==4.1.6
- jupyterlab==4.2.5
- nbgitpuller==1.2.1
- notebook==7.2.2
- syncthing==1.27.12
- pip:
  - git-credential-helpers==0.2
  - jupyter-shiny-proxy==1.1
  # Measure popularity of different packages in our hubs
  # https://discourse.jupyter.org/t/request-for-implementation-instrument-libraries-actively-used-by-users-on-a-jupyterhub/7994?u=yuvipanda
  #- git+https://github.com/shaneknapp/python-popularity-contest.git@add-error-handling
